*** Variables ***
${TERM_CONDITION_CHECKBOX}    id=termsofservice
${CHECKOUT_BUTTON}    id=checkout
${EDIT_ADDRESS_BUTTON}    id=edit-billing-address-button
${COUNTRY_DROPDOWN}    id=BillingNewAddress_CountryId
${STATE_DROPDOWN}    id=BillingNewAddress_StateProvinceId
${CITY_INPUT}    id=BillingNewAddress_City
${ADDRESS1_INPUT}    id=BillingNewAddress_Address1
${ZIP_INPUT}    id=BillingNewAddress_ZipPostalCode
${PHONE_INPUT}    id=BillingNewAddress_PhoneNumber
${ADDRESS_CONTINUE_BUTTON}    class=new-address-next-step-button
${SHIPPING_METHOD_RADIO}    shippingoption
${PAYMENT_METHOD_RADIO}    paymentmethod
${SHIPPING_METHOD_CONTINUE_BUTTON}    class=shipping-method-next-step-button
${PAYMENT_METHOD_LIST}    id=payment-method-block
${PAYMENT_METHOD_CONTINUE_BUTTON}    class=payment-method-next-step-button
${PAYMENT_INFO_CONTINUE_BUTTON}    class=payment-info-next-step-button
${CONFIRM_ORDER_BUTTON}    class=confirm-order-next-step-button


